server:
  port: 8010
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:mariadb://bookuluv.cmdeab77miub.ap-northeast-2.rds.amazonaws.com:3306/book_u_luv?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: buladmin
    password: 1q2w3e4r
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: create
logging:
  level:
    root: info
    com.sbp.bookuluv.app: info
    org.hibernate.type.descriptor.sql: info
custom:
  site:
    baseUrl: "https://www.bookuluv.devh.me"